### ISSUE TITLE
Ajout des tests dans le workflow

### ISSUE THREAD

**Issue by xReapex** [xReapex/angular_csid#6]
Réussir à lancer la commande de test dans le workflow

**Comment by ESKGit** [comment]
c'est bon j'ai fais laisse moi dormir

**Comment by xReapex** [comment]
![image](https://user-images.githubusercontent.com/56170171/150669765-724c2ccb-fa7e-40b9-9730-609b0580e946.png)
 
Erreur lors du lancement de test à régler
